const BASE_URL = "http://localhost:8000/v1";

export const API = {
  //LOGIN
  LOGIN_EMAIL: `${BASE_URL}`,
  LOGIN_PHONE: `${BASE_URL}`,
  // PRODUCT
  GET_ALL_PRODUCTS: `${BASE_URL}`,
  GET_ALL_PRODUCTS_W_DELETED: `${BASE_URL}`,
  GET_PRODUCT: `${BASE_URL}`,
  CREATE_PRODUCT: `${BASE_URL}`,
  UPDATE_PRODUCT: `${BASE_URL}`,
  DELETE_PRODUCT: `${BASE_URL}`,
  // BLOG
  GET_ALL_BLOGS: `${BASE_URL}`,
  CREATE_BLOG: `${BASE_URL}`,
  UPDATE_BLOG: `${BASE_URL}`,
  DELETE_BLOG: `${BASE_URL}`,
  // ACCOUNT
  GET_ALL_ACCOUNTS: `${BASE_URL}`,
  GET_CLIENT_ACCOUNT: `${BASE_URL}`,
  CREATE_CLIENT_ACCOUNTS: `${BASE_URL}`,
  UPDATE_CLIENT_ACCOUNTS: `${BASE_URL}`,
  DELETE_CLIENT_ACCOUNTS: `${BASE_URL}`,
  GET_ACCOUNT_BY_ID: `${BASE_URL}`,
  // ORDER
  GET_ALL_ORDERS: `${BASE_URL}`,
  UPDATE_ORDER: `${BASE_URL}`,
  DOWNLOAD_IMAGE: `${BASE_URL}`,
  CREATE: `${BASE_URL}`,
  DELETE_ORDER: `${BASE_URL}`,
  // DISCOUNT
  GET_ALL_DISCOUNTS: `${BASE_URL}`,
  GET_DISCOUNT: `${BASE_URL}`,
  CREATE_DISCOUNT: `${BASE_URL}`,
  UPDATE_DISCOUNT: `${BASE_URL}`,
  DELETE_DISCOUNT: `${BASE_URL}`,
  CHECK_DISCOUNT: `${BASE_URL}`,
};
